import { afterAll, beforeAll, beforeEach, describe, expect, it } from 'vitest';
import pg from 'pg';
import { migrate } from '../../packages/database/src/migrate.js';
import { SocialService, SocialError } from '../../packages/social/src/service.js';
import { buildApp } from '../../apps/api/src/app.js';
import { TestEmailAdapter } from '../../apps/api/src/email.js';
import type { FastifyInstance } from 'fastify';

const url=process.env.TEST_DATABASE_URL; const run=url?describe:describe.skip; let pool:pg.Pool; let social:SocialService; let app:FastifyInstance;
async function user(name:string,visibility:'PUBLIC'|'PRIVATE'='PUBLIC'){const u=await pool.query("INSERT INTO users(email_normalized) VALUES($1) RETURNING id",[`${name}@example.com`]);await pool.query('INSERT INTO profiles(user_id,username_normalized,display_name) VALUES($1,$2,$2)',[u.rows[0].id,name]);await pool.query('INSERT INTO privacy_settings(user_id,account_visibility) VALUES($1,$2)',[u.rows[0].id,visibility]);return u.rows[0].id as string}

run('Step 7 social graph on PostgreSQL',()=>{
 beforeAll(async()=>{pool=new pg.Pool({connectionString:url});await pool.query('DROP SCHEMA public CASCADE; CREATE SCHEMA public');await migrate(url!);social=new SocialService(pool);app=await buildApp({pool,email:new TestEmailAdapter()});await app.ready()});afterAll(async()=>{await app.close();await pool.end()});beforeEach(async()=>{await pool.query('TRUNCATE outbox_events, mutes, blocks, follow_requests, follows, privacy_settings, profiles, user_credentials, sessions, users CASCADE')});
 it('follows public accounts idempotently and unfollows',async()=>{const a=await user('alice'),b=await user('bob');expect((await social.follow(a,b,'r1')).state).toBe('FOLLOWING');expect((await social.follow(a,b,'r2')).state).toBe('FOLLOWING');expect((await pool.query('SELECT * FROM follows')).rowCount).toBe(1);await social.unfollow(a,b,'r3');expect((await pool.query('SELECT * FROM follows')).rowCount).toBe(0)});
 it('requests private accounts and approves, rejects, and cancels with ownership enforcement',async()=>{const a=await user('alice'),b=await user('bob','PRIVATE'),c=await user('cara');await social.follow(a,b,'r1');await social.follow(a,b,'r2');let q=await pool.query("SELECT id FROM follow_requests WHERE status='PENDING'");expect(q.rowCount).toBe(1);await expect(social.resolveRequest(c,q.rows[0].id,'APPROVED','r3')).rejects.toBeInstanceOf(SocialError);await social.resolveRequest(b,q.rows[0].id,'APPROVED','r4');expect((await pool.query('SELECT * FROM follows')).rowCount).toBe(1);await social.unfollow(a,b,'r5');await social.follow(a,b,'r6');q=await pool.query("SELECT id FROM follow_requests WHERE status='PENDING'");await social.resolveRequest(b,q.rows[0].id,'REJECTED','r7');await social.follow(a,b,'r8');q=await pool.query("SELECT id FROM follow_requests WHERE status='PENDING'");await social.cancelRequest(a,q.rows[0].id,'r9');expect((await pool.query("SELECT * FROM follow_requests WHERE status='PENDING'")).rowCount).toBe(0)});
 it('atomically converts pending requests when becoming public',async()=>{const target=await user('target','PRIVATE'),a=await user('alice'),b=await user('bob');await Promise.all([social.follow(a,target,'r1'),social.follow(b,target,'r2')]);await social.makePublic(target,'r3');expect((await pool.query('SELECT * FROM follows WHERE followed_id=$1',[target])).rowCount).toBe(2);expect((await pool.query("SELECT * FROM follow_requests WHERE target_id=$1 AND status='PENDING'",[target])).rowCount).toBe(0)});
 it('removes a follower and requires a new private request',async()=>{const a=await user('alice'),b=await user('bob');await social.follow(a,b,'r1');await pool.query("UPDATE privacy_settings SET account_visibility='PRIVATE' WHERE user_id=$1",[b]);await social.removeFollower(b,a,'r2');expect((await social.follow(a,b,'r3')).state).toBe('REQUESTED')});
 it('block removes both directions and pending requests; unblock restores none',async()=>{const a=await user('alice'),b=await user('bob');await social.follow(a,b,'r1');await social.follow(b,a,'r2');await social.block(a,b,'r3');expect((await pool.query('SELECT * FROM follows')).rowCount).toBe(0);await expect(social.follow(b,a,'r4')).rejects.toMatchObject({code:'NOT_FOUND'});await social.unblock(a,b,'r5');expect((await pool.query('SELECT * FROM follows')).rowCount).toBe(0)});
 it('mute is private, idempotent, and does not remove follows',async()=>{const a=await user('alice'),b=await user('bob');await social.follow(a,b,'r1');await social.mute(a,b);await social.mute(a,b);expect((await pool.query('SELECT * FROM mutes WHERE muter_id=$1',[a])).rowCount).toBe(1);expect((await pool.query('SELECT * FROM mutes WHERE muter_id=$1',[b])).rowCount).toBe(0);expect((await pool.query('SELECT * FROM follows')).rowCount).toBe(1);await social.unmute(a,b);expect((await pool.query('SELECT * FROM mutes')).rowCount).toBe(0)});
 it('serializes simultaneous follows and block versus follow',async()=>{const a=await user('alice'),b=await user('bob');await Promise.all(Array.from({length:8},(_,i)=>social.follow(a,b,`r${i}`)));expect((await pool.query('SELECT * FROM follows')).rowCount).toBe(1);await Promise.allSettled([social.follow(b,a,'follow'),social.block(a,b,'block')]);expect((await pool.query('SELECT * FROM follows')).rowCount).toBe(0);expect((await pool.query('SELECT * FROM blocks')).rowCount).toBe(1)});
 it('database constraints reject self relationships',async()=>{const a=await user('alice');await expect(pool.query('INSERT INTO follows(follower_id,followed_id) VALUES($1,$1)',[a])).rejects.toMatchObject({code:'23514'});await expect(pool.query('INSERT INTO blocks(blocker_id,blocked_id) VALUES($1,$1)',[a])).rejects.toMatchObject({code:'23514'});await expect(pool.query('INSERT INTO mutes(muter_id,muted_id) VALUES($1,$1)',[a])).rejects.toMatchObject({code:'23514'})});
 it('enforces private profile redaction and unauthenticated mutation rejection at HTTP boundary',async()=>{await user('alice','PRIVATE');const profile=await app.inject({method:'GET',url:'/v1/users/alice'});expect(profile.statusCode).toBe(200);expect(profile.json().data).not.toHaveProperty('bio');const mutation=await app.inject({method:'POST',url:'/v1/users/alice/follow',headers:{origin:'http://localhost:3000','x-csrf-token':'forged'}});expect(mutation.statusCode).toBe(401)});
});

run('Step 7 concurrency and authorization regressions',()=>{
 beforeAll(async()=>{pool=new pg.Pool({connectionString:url});await pool.query('DROP SCHEMA public CASCADE; CREATE SCHEMA public');await migrate(url!);social=new SocialService(pool)});afterAll(async()=>{await pool.end()});beforeEach(async()=>{await pool.query('TRUNCATE outbox_events, mutes, blocks, follow_requests, follows, privacy_settings, profiles, user_credentials, sessions, users CASCADE')});
 it('leaves a valid state after follow races with unfollow',async()=>{const a=await user('racea'),b=await user('raceb');await Promise.allSettled([social.follow(a,b,'follow'),social.unfollow(a,b,'unfollow')]);expect((await pool.query('SELECT count(*)::int AS count FROM follows WHERE follower_id=$1 AND followed_id=$2',[a,b])).rows[0].count).toBeLessThanOrEqual(1)});
 it('serializes approve against requester cancellation',async()=>{const a=await user('requester'),b=await user('private','PRIVATE');await social.follow(a,b,'request');const id=(await pool.query("SELECT id FROM follow_requests WHERE status='PENDING'")).rows[0].id;await Promise.allSettled([social.resolveRequest(b,id,'APPROVED','approve'),social.cancelRequest(a,id,'cancel')]);const request=await pool.query('SELECT status,resolved_at FROM follow_requests WHERE id=$1',[id]);expect(['APPROVED','CANCELLED']).toContain(request.rows[0].status);expect(request.rows[0].resolved_at).not.toBeNull()});
 it('serializes block against a pending request',async()=>{const a=await user('blocker'),b=await user('private','PRIVATE');await Promise.allSettled([social.follow(a,b,'request'),social.block(b,a,'block')]);expect((await pool.query('SELECT * FROM follows WHERE follower_id=$1 AND followed_id=$2',[a,b])).rowCount).toBe(0);expect((await pool.query("SELECT * FROM follow_requests WHERE requester_id=$1 AND target_id=$2 AND status='PENDING'",[a,b])).rowCount).toBe(0)});
 it('serializes private-to-public conversion against request creation',async()=>{const a=await user('convertrequester'),b=await user('converttarget','PRIVATE');await Promise.allSettled([social.follow(a,b,'request'),social.makePublic(b,'public')]);expect((await pool.query("SELECT account_visibility FROM privacy_settings WHERE user_id=$1",[b])).rows[0].account_visibility).toBe('PUBLIC');expect((await pool.query("SELECT * FROM follow_requests WHERE requester_id=$1 AND target_id=$2 AND status='PENDING'",[a,b])).rowCount).toBe(0);expect((await pool.query('SELECT * FROM follows WHERE follower_id=$1 AND followed_id=$2',[a,b])).rowCount).toBe(1)});
 it('prevents foreign reject and follower removal from changing another account',async()=>{const a=await user('owner'),b=await user('requester2'),c=await user('attacker');await pool.query("UPDATE privacy_settings SET account_visibility='PRIVATE' WHERE user_id=$1",[a]);await social.follow(b,a,'request');const id=(await pool.query("SELECT id FROM follow_requests WHERE status='PENDING'")).rows[0].id;await expect(social.resolveRequest(c,id,'REJECTED','forged')).rejects.toMatchObject({code:'NOT_FOUND'});await social.resolveRequest(a,id,'APPROVED','approve');await social.removeFollower(c,b,'forged-remove');expect((await pool.query('SELECT * FROM follows WHERE follower_id=$1 AND followed_id=$2',[b,a])).rowCount).toBe(1)});
});
