import { randomUUID } from 'node:crypto';
import Fastify, { type FastifyInstance, type FastifyReply, type FastifyRequest } from 'fastify';
import cookie from '@fastify/cookie'; import cors from '@fastify/cors'; import rateLimit from '@fastify/rate-limit';
import type { Pool, PoolClient } from 'pg';
import { hashPassword, hashToken, issueToken, verifyPassword } from '../../../packages/auth/src/crypto.js';
import { mayAuthenticate, normalizeEmail } from '../../../packages/auth/src/policy.js';
import { changePasswordSchema, deleteSchema, emailSchema, loginSchema, privacySchema, profileSchema, registerSchema, resetSchema, tokenSchema } from '../../../packages/auth/src/schemas.js';
import { ADMIN_COOKIE, clearConsumerCookies, CONSUMER_COOKIE, CSRF_COOKIE, setConsumerCookies } from '../../../packages/auth/src/session.js';
import type { EmailAdapter } from './email.js';

type Deps={pool:Pool,email:EmailAdapter}; const genericAuth={code:'INVALID_CREDENTIALS',message:'Email or password is invalid.'};
function fail(reply:FastifyReply,status:number,code:string,message:string,requestId:string){return reply.code(status).send({error:{code,message,request_id:requestId}})}
async function tx<T>(pool:Pool, fn:(c:PoolClient)=>Promise<T>):Promise<T>{const c=await pool.connect();try{await c.query('BEGIN');const v=await fn(c);await c.query('COMMIT');return v}catch(e){await c.query('ROLLBACK');throw e}finally{c.release()}}
async function emit(c:PoolClient,type:string,userId:string,requestId:string,payload:object={}){await c.query('INSERT INTO outbox_events(event_type,aggregate_type,aggregate_id,payload,request_id) VALUES($1,$2,$3,$4,$5)',[type,'User',userId,payload,requestId])}

export async function buildApp({pool,email}:Deps):Promise<FastifyInstance>{const app=Fastify({logger:false,genReqId:()=>randomUUID()});
 await app.register(cookie); await app.register(cors,{origin:[process.env.APP_ORIGIN??'http://localhost:3000'],credentials:true}); await app.register(rateLimit,{global:false});
 app.addHook('onRequest',async req=>{req.requestId=req.id});
 app.setErrorHandler((error,req,reply)=>{if((error as {validation?:unknown}).validation)return fail(reply,400,'VALIDATION_ERROR','The request is invalid.',req.requestId);return fail(reply,500,'INTERNAL_ERROR','An unexpected error occurred.',req.requestId)});
 const limited={config:{rateLimit:{max:10,timeWindow:'1 minute'}}};
 async function consumer(req:FastifyRequest,reply:FastifyReply){const raw=req.cookies[CONSUMER_COOKIE];if(!raw)return fail(reply,401,'UNAUTHENTICATED','Authentication is required.',req.requestId);const q=await pool.query("SELECT s.id,s.user_id,s.realm,u.account_state FROM sessions s JOIN users u ON u.id=s.user_id WHERE s.token_hash=$1 AND s.realm='CONSUMER' AND s.audience='wyn-consumer' AND s.revoked_at IS NULL AND s.expires_at>now()",[hashToken(raw)]);const row=q.rows[0];if(!row||!mayAuthenticate(row.account_state))return fail(reply,401,'UNAUTHENTICATED','Authentication is required.',req.requestId);req.auth={userId:row.user_id,sessionId:row.id,realm:'CONSUMER',state:row.account_state};await pool.query('UPDATE sessions SET last_used_at=now() WHERE id=$1 AND last_used_at < now()-interval \'5 minutes\'',[row.id]);}
 async function csrf(req:FastifyRequest,reply:FastifyReply){if(!req.auth)return;const origin=req.headers.origin;const supplied=req.headers['x-csrf-token'];const raw=req.cookies[CSRF_COOKIE];if(origin!==(process.env.APP_ORIGIN??'http://localhost:3000')||typeof supplied!=='string'||!raw||supplied!==raw)return fail(reply,403,'CSRF_INVALID','Request authenticity could not be verified.',req.requestId);const q=await pool.query('SELECT 1 FROM sessions WHERE id=$1 AND csrf_token_hash=$2',[req.auth.sessionId,hashToken(raw)]);if(!q.rowCount)return fail(reply,403,'CSRF_INVALID','Request authenticity could not be verified.',req.requestId)}

 app.post('/v1/auth/register',{...limited},async(req,reply)=>{const p=registerSchema.parse(req.body);try{await tx(pool,async c=>{const u=await c.query('INSERT INTO users(email_normalized) VALUES($1) RETURNING id',[normalizeEmail(p.email)]);const id=u.rows[0].id;await c.query('INSERT INTO user_credentials(user_id,password_hash) VALUES($1,$2)',[id,await hashPassword(p.password)]);await c.query('INSERT INTO profiles(user_id,username_normalized,display_name) VALUES($1,$2,$3)',[id,p.username,p.displayName]);await c.query('INSERT INTO privacy_settings(user_id) VALUES($1)',[id]);const token=issueToken();await c.query("INSERT INTO email_verification_tokens(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '24 hours')",[id,token.hash]);await emit(c,'UserRegistered',id,req.requestId);await emit(c,'EmailVerificationRequested',id,req.requestId);await email.send({to:normalizeEmail(p.email),template:'VERIFY_EMAIL',token:token.raw})});return reply.code(202).send({data:{message:'Registration accepted. Check your email.'},request_id:req.requestId})}catch(e){if((e as {code?:string}).code==='23505')return fail(reply,409,'ACCOUNT_CONFLICT','The email or username is unavailable.',req.requestId);throw e}});
 app.post('/v1/auth/login',{...limited},async(req,reply)=>{const p=loginSchema.parse(req.body);const q=await pool.query('SELECT u.id,u.account_state,c.password_hash FROM users u JOIN user_credentials c ON c.user_id=u.id WHERE u.email_normalized=$1',[normalizeEmail(p.email)]);const u=q.rows[0];if(!u||!mayAuthenticate(u.account_state)||!(await verifyPassword(u.password_hash,p.password))){return reply.code(401).send({error:{...genericAuth,request_id:req.requestId}})}const token=issueToken(),csrfToken=issueToken();await tx(pool,async c=>{await c.query("INSERT INTO sessions(user_id,token_hash,realm,audience,csrf_token_hash,label,expires_at) VALUES($1,$2,'CONSUMER','wyn-consumer',$3,$4,now()+interval '30 days')",[u.id,token.hash,csrfToken.hash,p.deviceLabel??null]);await c.query("INSERT INTO security_events(user_id,event_type,request_id) VALUES($1,'LOGIN_SUCCEEDED',$2)",[u.id,req.requestId])});setConsumerCookies(reply,token.raw,csrfToken.raw);return reply.send({data:{authenticated:true},request_id:req.requestId})});
 app.post('/v1/auth/logout',{preHandler:[consumer,csrf]},async(req,reply)=>{if(!req.auth)return;await pool.query("UPDATE sessions SET revoked_at=now(),revocation_reason='LOGOUT' WHERE id=$1",[req.auth.sessionId]);clearConsumerCookies(reply);return reply.code(204).send()});
 app.post('/v1/auth/logout-all',{preHandler:[consumer,csrf]},async(req,reply)=>{if(!req.auth)return;await pool.query("UPDATE sessions SET revoked_at=now(),revocation_reason='LOGOUT_ALL' WHERE user_id=$1 AND realm='CONSUMER' AND revoked_at IS NULL",[req.auth.userId]);clearConsumerCookies(reply);return reply.code(204).send()});
 app.post('/v1/auth/verify-email',{...limited},async(req,reply)=>{const p=tokenSchema.parse(req.body);const ok=await tx(pool,async c=>{const q=await c.query('SELECT id,user_id FROM email_verification_tokens WHERE token_hash=$1 AND consumed_at IS NULL AND expires_at>now() FOR UPDATE',[hashToken(p.token)]);if(!q.rowCount)return false;await c.query('UPDATE email_verification_tokens SET consumed_at=now() WHERE id=$1',[q.rows[0].id]);await c.query('UPDATE users SET email_verified_at=COALESCE(email_verified_at,now()),updated_at=now() WHERE id=$1',[q.rows[0].user_id]);await emit(c,'EmailVerified',q.rows[0].user_id,req.requestId);return true});if(!ok)return fail(reply,400,'TOKEN_INVALID','The token is invalid or expired.',req.requestId);return reply.send({data:{verified:true},request_id:req.requestId})});
 app.post('/v1/auth/resend-verification',{...limited},async(req,reply)=>{const p=emailSchema.parse(req.body);const q=await pool.query('SELECT id,email_verified_at FROM users WHERE email_normalized=$1',[normalizeEmail(p.email)]);if(q.rowCount&&!q.rows[0].email_verified_at){const t=issueToken();await tx(pool,async c=>{await c.query("INSERT INTO email_verification_tokens(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '24 hours')",[q.rows[0].id,t.hash]);await emit(c,'EmailVerificationRequested',q.rows[0].id,req.requestId)});await email.send({to:normalizeEmail(p.email),template:'VERIFY_EMAIL',token:t.raw})}return reply.code(202).send({data:{message:'If eligible, an email will be sent.'},request_id:req.requestId})});
 app.post('/v1/auth/forgot-password',{...limited},async(req,reply)=>{const p=emailSchema.parse(req.body);const q=await pool.query("SELECT id FROM users WHERE email_normalized=$1 AND account_state IN ('ACTIVE','RESTRICTED')",[normalizeEmail(p.email)]);if(q.rowCount){const t=issueToken();await tx(pool,async c=>{await c.query("INSERT INTO password_reset_tokens(user_id,token_hash,expires_at) VALUES($1,$2,now()+interval '1 hour')",[q.rows[0].id,t.hash]);await emit(c,'PasswordResetRequested',q.rows[0].id,req.requestId)});await email.send({to:normalizeEmail(p.email),template:'PASSWORD_RESET',token:t.raw})}return reply.code(202).send({data:{message:'If the account is eligible, an email will be sent.'},request_id:req.requestId})});
 app.post('/v1/auth/reset-password',{...limited},async(req,reply)=>{const p=resetSchema.parse(req.body);const changed=await tx(pool,async c=>{const q=await c.query('SELECT id,user_id FROM password_reset_tokens WHERE token_hash=$1 AND consumed_at IS NULL AND expires_at>now() FOR UPDATE',[hashToken(p.token)]);if(!q.rowCount)return null;const {id,user_id}=q.rows[0];await c.query('UPDATE password_reset_tokens SET consumed_at=now() WHERE id=$1',[id]);await c.query('UPDATE user_credentials SET password_hash=$1,password_changed_at=now(),updated_at=now() WHERE user_id=$2',[await hashPassword(p.password),user_id]);await c.query("UPDATE sessions SET revoked_at=now(),revocation_reason='PASSWORD_RESET' WHERE user_id=$1 AND revoked_at IS NULL",[user_id]);await emit(c,'PasswordChanged',user_id,req.requestId,{method:'reset'});return user_id});if(!changed)return fail(reply,400,'TOKEN_INVALID','The token is invalid or expired.',req.requestId);return reply.send({data:{changed:true},request_id:req.requestId})});
 app.post('/v1/auth/change-password',{preHandler:[consumer,csrf]},async(req,reply)=>{if(!req.auth)return;const p=changePasswordSchema.parse(req.body);const q=await pool.query('SELECT password_hash FROM user_credentials WHERE user_id=$1',[req.auth.userId]);if(!(await verifyPassword(q.rows[0].password_hash,p.currentPassword)))return reply.code(401).send({error:{...genericAuth,request_id:req.requestId}});await tx(pool,async c=>{await c.query('UPDATE user_credentials SET password_hash=$1,password_changed_at=now(),updated_at=now() WHERE user_id=$2',[await hashPassword(p.newPassword),req.auth!.userId]);await c.query("UPDATE sessions SET revoked_at=now(),revocation_reason='PASSWORD_CHANGE' WHERE user_id=$1 AND id<>$2 AND revoked_at IS NULL",[req.auth!.userId,req.auth!.sessionId]);await emit(c,'PasswordChanged',req.auth!.userId,req.requestId,{method:'authenticated'})});await email.send({to:'redacted',template:'PASSWORD_CHANGED'});return reply.send({data:{changed:true},request_id:req.requestId})});
 app.get('/v1/me',{preHandler:[consumer]},async(req,reply)=>{if(!req.auth)return;const q=await pool.query('SELECT p.username_normalized AS username,p.display_name,p.bio,p.website,p.location,p.avatar_url,p.cover_url,p.created_at,ps.account_visibility,u.email_verified_at FROM profiles p JOIN users u ON u.id=p.user_id JOIN privacy_settings ps ON ps.user_id=p.user_id WHERE p.user_id=$1',[req.auth.userId]);return reply.send({data:q.rows[0],request_id:req.requestId})});
 app.patch('/v1/me/profile',{preHandler:[consumer,csrf]},async(req,reply)=>{if(!req.auth)return;const p=profileSchema.parse(req.body);const q=await pool.query('UPDATE profiles SET display_name=COALESCE($1,display_name),bio=COALESCE($2,bio),website=CASE WHEN $3 THEN $4 ELSE website END,location=CASE WHEN $5 THEN $6 ELSE location END,updated_at=now() WHERE user_id=$7 RETURNING username_normalized AS username,display_name,bio,website,location,avatar_url,cover_url,created_at',[p.displayName??null,p.bio??null,'website' in p,p.website??null,'location' in p,p.location??null,req.auth.userId]);return reply.send({data:q.rows[0],request_id:req.requestId})});
 app.get('/v1/me/sessions',{preHandler:[consumer]},async(req,reply)=>{if(!req.auth)return;const q=await pool.query("SELECT id,label,created_at,last_used_at,expires_at,(id=$2) AS current FROM sessions WHERE user_id=$1 AND realm='CONSUMER' AND revoked_at IS NULL AND expires_at>now() ORDER BY created_at DESC",[req.auth.userId,req.auth.sessionId]);return reply.send({data:q.rows,request_id:req.requestId})});
 app.delete('/v1/me/sessions/:sessionId',{preHandler:[consumer,csrf]},async(req,reply)=>{if(!req.auth)return;const id=(req.params as {sessionId:string}).sessionId;const q=await pool.query("UPDATE sessions SET revoked_at=now(),revocation_reason='USER_REVOKED' WHERE id=$1 AND user_id=$2 AND realm='CONSUMER' AND revoked_at IS NULL RETURNING id",[id,req.auth.userId]);if(!q.rowCount)return fail(reply,404,'NOT_FOUND','The session is unavailable.',req.requestId);return reply.code(204).send()});
 app.patch('/v1/me/privacy',{preHandler:[consumer,csrf]},async(req,reply)=>{if(!req.auth)return;const p=privacySchema.parse(req.body);const q=await pool.query('UPDATE privacy_settings SET account_visibility=$1,updated_at=now() WHERE user_id=$2 RETURNING account_visibility',[p.accountVisibility,req.auth.userId]);return reply.send({data:q.rows[0],request_id:req.requestId})});
 app.post('/v1/me/delete-request',{preHandler:[consumer,csrf]},async(req,reply)=>{if(!req.auth)return;const p=deleteSchema.parse(req.body);const q=await pool.query('SELECT password_hash FROM user_credentials WHERE user_id=$1',[req.auth.userId]);if(!(await verifyPassword(q.rows[0].password_hash,p.currentPassword)))return reply.code(401).send({error:{...genericAuth,request_id:req.requestId}});await tx(pool,async c=>{await c.query('INSERT INTO account_deletion_requests(user_id) VALUES($1) ON CONFLICT DO NOTHING',[req.auth!.userId]);await c.query("UPDATE users SET account_state='DELETION_PENDING',updated_at=now() WHERE id=$1",[req.auth!.userId]);await c.query("UPDATE sessions SET revoked_at=now(),revocation_reason='DELETION_PENDING' WHERE user_id=$1 AND revoked_at IS NULL",[req.auth!.userId]);await emit(c,'AccountDeletionRequested',req.auth!.userId,req.requestId)});clearConsumerCookies(reply);return reply.code(202).send({data:{state:'DELETION_PENDING'},request_id:req.requestId})});
 app.get('/v1/users/:username',async(req,reply)=>{const username=(req.params as {username:string}).username.trim().toLowerCase();const q=await pool.query("SELECT p.username_normalized AS username,p.display_name,p.bio,p.website,p.location,p.avatar_url,p.cover_url,p.created_at,ps.account_visibility FROM profiles p JOIN users u ON u.id=p.user_id JOIN privacy_settings ps ON ps.user_id=p.user_id WHERE p.username_normalized=$1 AND u.account_state IN ('ACTIVE','RESTRICTED')",[username]);if(!q.rowCount)return fail(reply,404,'NOT_FOUND','The profile is unavailable.',req.requestId);return reply.send({data:{...q.rows[0],is_private:q.rows[0].account_visibility==='PRIVATE'},request_id:req.requestId})});
 app.get('/admin/v1/session',async(req,reply)=>{const raw=req.cookies[ADMIN_COOKIE];if(!raw)return fail(reply,401,'ADMIN_UNAUTHENTICATED','Admin authentication is required.',req.requestId);const q=await pool.query("SELECT 1 FROM sessions s JOIN admin_principals a ON a.user_id=s.user_id WHERE s.token_hash=$1 AND s.realm='ADMIN' AND s.audience='wyn-admin' AND a.enabled AND s.revoked_at IS NULL AND s.expires_at>now()",[hashToken(raw)]);if(!q.rowCount)return fail(reply,401,'ADMIN_UNAUTHENTICATED','Admin authentication is required.',req.requestId);return reply.send({data:{authenticated:true},request_id:req.requestId})});
 return app;}
